import { chromium,browserOptions,appUrl } from './browser-runtime.mjs';
import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
const browser=await chromium.launch(browserOptions),context=await browser.newContext({acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
async function unlock(p,pin='0427'){await p.getByLabel('Four-digit PIN',{exact:true}).fill(pin);await p.getByRole('button',{name:'Unlock notes',exact:true}).click();await p.getByRole('button',{name:'Lock notes',exact:true}).waitFor();}
try{
 await page.goto(appUrl);await page.getByLabel('Search chief complaints').fill('Chest pain');await page.getByRole('button',{name:'Start note · write in this template',exact:true}).click();
 await page.getByLabel('Four-digit PIN',{exact:true}).fill('0427');await page.getByLabel('Confirm PIN',{exact:true}).fill('0427');await page.getByRole('button',{name:'Create local vault',exact:true}).click();
 await page.getByLabel('Patient name',{exact:true}).fill('FOLIO TEST PATIENT');await page.getByLabel('Code status',{exact:true}).selectOption('Unknown / not yet confirmed');await page.getByLabel('#1 emergency contact - name',{exact:true}).fill('TEST CONTACT');await page.getByLabel('#1 emergency contact - phone',{exact:true}).fill('555-0100');
 await page.locator('summary').filter({hasText:'Subjective / HPI'}).click();await page.getByLabel('Record pain score',{exact:true}).check();assert.equal(await page.getByRole('slider',{name:'Pain severity (0-10)',exact:true}).inputValue(),'0');
 await page.locator('summary').filter({hasText:'Symptoms / review of systems'}).click();await page.locator('#ros-0').selectOption('Denied');await page.getByText('Saved on this device',{exact:true}).waitFor();
 const raw=await page.evaluate(()=>Object.entries(localStorage).find(([k])=>k.startsWith('folio-vault-v1:'))?.[1]);assert(raw);assert(!raw.includes('FOLIO TEST PATIENT'));assert(!raw.includes('TEST CONTACT'));
 const d=page.waitForEvent('download');await page.getByRole('button',{name:'Download completed PDF',exact:true}).click();assert((await d).suggestedFilename().startsWith('folio-note-'));
 const b=page.waitForEvent('download');await page.getByRole('button',{name:'Encrypted backup',exact:true}).click();const backupText=await readFile(await(await b).path(),'utf8');
 await page.getByRole('button',{name:'Lock notes',exact:true}).click();await page.getByRole('button',{name:'Unlock notes',exact:true}).waitFor();assert.equal(await page.getByLabel('Patient name',{exact:true}).count(),0);
 await page.getByLabel('Four-digit PIN',{exact:true}).fill('9999');await page.getByRole('button',{name:'Unlock notes',exact:true}).click();await page.getByText(/Could not unlock or save/).waitFor();
 await unlock(page);await page.getByRole('button',{name:/FOLIO TEST PATIENT/}).click();assert.equal(await page.getByLabel('Patient name',{exact:true}).inputValue(),'FOLIO TEST PATIENT');
 await page.reload();await page.getByRole('tab',{name:'My notes',exact:true}).click();await unlock(page);await page.getByRole('button',{name:/FOLIO TEST PATIENT/}).click();
 const second=await context.newPage();await second.goto(appUrl);await second.getByRole('tab',{name:'My notes',exact:true}).click();await second.getByLabel('Four-digit PIN',{exact:true}).fill('0427');await second.getByRole('button',{name:'Unlock notes',exact:true}).click();await second.getByText(/Notes are open in another tab/).waitFor();await second.close();
 await context.setOffline(true);await page.reload();await unlock(page);await page.getByRole('button',{name:/FOLIO TEST PATIENT/}).click();assert.equal(await page.getByLabel('Patient name',{exact:true}).inputValue(),'FOLIO TEST PATIENT');
 await page.clock.install();await page.getByRole('heading',{name:'My notes',exact:true}).click();await page.clock.fastForward(300001);await page.getByRole('button',{name:'Unlock notes',exact:true}).waitFor();await unlock(page);await page.getByRole('button',{name:/FOLIO TEST PATIENT/}).click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'tmp/notes-mobile.png',fullPage:true});await page.setViewportSize({width:1400,height:1000});await page.screenshot({path:'tmp/notes-desktop.png',fullPage:true});
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});await page.getByLabel('Patient name',{exact:true}).fill('UNSAVED TEST');await page.getByText(/Not saved —/).waitFor();await page.getByRole('button',{name:'Lock notes',exact:true}).click();await page.getByText(/Your unsaved note is hidden/).waitFor();await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;});await unlock(page);await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.getByText('Saved on this device',{exact:true}).waitFor();assert.equal(await page.getByLabel('Patient name',{exact:true}).inputValue(),'UNSAVED TEST');
 await page.getByRole('button',{name:'Move to trash',exact:true}).click();await page.getByRole('button',{name:'Trash',exact:true}).click();await page.getByRole('button',{name:/UNSAVED TEST/}).click();await page.getByRole('button',{name:'Restore note',exact:true}).click();await page.getByRole('button',{name:'Lock notes',exact:true}).click();
 const clean=await browser.newContext();const restored=await clean.newPage();await restored.goto(appUrl);await restored.getByRole('tab',{name:'My notes',exact:true}).click();await restored.getByLabel('Restore encrypted backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backupText)});await restored.getByLabel('Four-digit PIN',{exact:true}).fill('0427');await restored.getByRole('button',{name:'Unlock notes',exact:true}).click();await restored.getByRole('button',{name:/FOLIO TEST PATIENT/}).waitFor();await clean.close();assert.deepEqual(errors,[]);
 console.log('PASS notes: encryption, fields, PDF, backup, wrong PIN, reload, concurrent tabs, failed-save recovery, trash, restore, mobile');
}finally{await browser.close();}
