// Explicit, versioned choices for every built-in focused chief complaint.
// Conditional: screen for pain and complete its dimensions only when present.
// These choices are content decisions, not a claim of clinical validation.
export type PainMode = 'primary' | 'conditional' | 'none';
export const complaintPain: Record<string, PainMode> = {
  "Fever": "conditional",
  "Fatigue": "conditional",
  "Unintentional weight loss": "conditional",
  "Night sweats": "conditional",
  "Chest pain": "primary",
  "Palpitations": "conditional",
  "Syncope": "conditional",
  "Leg swelling": "conditional",
  "Cough": "conditional",
  "Shortness of breath": "conditional",
  "Wheezing": "conditional",
  "Hemoptysis": "conditional",
  "Abdominal pain": "primary",
  "Nausea & vomiting": "conditional",
  "Diarrhea": "conditional",
  "Constipation": "conditional",
  "Headache": "primary",
  "Dizziness / vertigo": "conditional",
  "Weakness": "conditional",
  "Numbness / tingling": "conditional",
  "Low back pain": "primary",
  "Knee pain": "primary",
  "Shoulder pain": "primary",
  "Multiple joint pain": "primary",
  "Painful urination": "primary",
  "Blood in urine": "conditional",
  "Flank pain": "primary",
  "Urinary frequency": "conditional",
  "Pelvic pain": "primary",
  "Abnormal vaginal bleeding": "conditional",
  "Vaginal discharge": "conditional",
  "Missed period / pregnancy concern": "conditional",
  "Excessive thirst / urination": "conditional",
  "Heat intolerance": "none",
  "Cold intolerance": "none",
  "Weight gain": "none",
  "Rash": "conditional",
  "Pruritus": "conditional",
  "Changing skin lesion": "conditional",
  "Skin redness / swelling": "conditional",
  "Sore throat": "primary",
  "Ear pain": "primary",
  "Nasal congestion / sinus pressure": "primary",
  "Hearing loss / tinnitus": "conditional",
  "Red eye": "conditional",
  "Vision loss / blurred vision": "conditional",
  "Eye pain": "primary",
  "Double vision": "conditional",
  "Low mood": "none",
  "Anxiety / panic": "none",
  "Insomnia": "none",
  "Hallucinations / unusual beliefs": "none",
  "Child with fever": "conditional",
  "Child with cough / wheeze": "conditional",
  "Child with vomiting / diarrhea": "conditional",
  "Child with rash": "conditional",
  "Easy bruising / bleeding": "conditional",
  "Enlarged lymph node": "conditional",
  "Pallor / anemia concern": "conditional",
  "Recurrent infections": "conditional",
  "Dehydration / poor intake": "conditional",
  "Elevated blood pressure": "conditional",
  "Sleep apnea concern": "conditional",
  "Heartburn / reflux": "primary",
  "Seizure / seizure-like episode": "conditional",
  "Neck pain": "primary",
  "Urinary incontinence": "conditional",
  "Breast lump / breast pain": "primary",
  "Diabetes follow-up": "conditional",
  "Acne": "conditional",
  "Epistaxis": "conditional",
  "Flashes / floaters": "conditional",
  "Memory / cognitive concern": "none",
  "Poor growth / weight gain": "none",
  "Anticoagulant follow-up / bleeding concern": "conditional",
  "Seasonal allergy symptoms": "none",
  "Medication side effects": "conditional",
  "Recurrent falls": "conditional",
  "Muscle cramps": "primary",
  "Snoring": "conditional",
  "Bloating / excess gas": "conditional",
  "Heel pain": "primary",
  "Hair shedding": "none",
  "Painful mouth sores": "primary",
  "Excessive daytime sleepiness": "conditional",
  "Minor head injury": "conditional",
  "Laceration / open wound": "primary",
  "Ankle injury": "primary",
  "Allergic reaction / hives": "conditional",
  "Acute dental pain": "primary",
  "Foreign body in skin": "primary",
  "Burn injury": "primary",
  "Alcohol intoxication concern": "conditional",
  "Acute back strain": "primary",
  "Painful skin abscess": "primary",
  "Breathlessness on exertion": "conditional",
  "Low blood pressure / lightheadedness": "conditional",
  "Slow heart rate": "conditional",
  "Fast heart rate": "conditional",
  "Irregular pulse alert": "conditional",
  "Heart murmur concern": "conditional",
  "Leg pain with walking": "primary",
  "Rapid weight gain / fluid retention": "conditional",
  "Dizziness on standing": "conditional",
  "Reduced exercise tolerance": "conditional",
  "Asthma symptom flare": "conditional",
  "COPD symptom worsening": "conditional",
  "Persistent sputum production": "conditional",
  "Pain with breathing": "primary",
  "Low oxygen reading": "conditional",
  "Recurrent chest infections": "conditional",
  "Lung nodule consultation": "conditional",
  "Abnormal chest imaging": "conditional",
  "CPAP intolerance": "conditional",
  "Cough after meals": "conditional",
  "Groin bulge": "conditional",
  "Umbilical bulge": "conditional",
  "Right upper abdominal pain": "primary",
  "Painful hemorrhoid concern": "primary",
  "Pilonidal pain / drainage": "primary",
  "Soft tissue lump": "conditional",
  "Postoperative wound concern": "conditional",
  "Incisional bulge": "conditional",
  "Gallstone consultation": "conditional",
  "Recurrent perianal drainage": "conditional",
  "Difficulty swallowing": "conditional",
  "Rectal bleeding": "conditional",
  "Black stools": "conditional",
  "Upper abdominal discomfort": "primary",
  "Yellow skin / eyes": "conditional",
  "Elevated liver enzymes": "conditional",
  "Early fullness after eating": "conditional",
  "Fecal urgency / leakage": "conditional",
  "Recurrent lower abdominal cramping": "primary",
  "Anal pain": "primary",
  "Tremor": "none",
  "Balance difficulty": "conditional",
  "Facial weakness": "conditional",
  "Burning feet": "primary",
  "Radiating leg pain": "primary",
  "Transient neurologic episode": "conditional",
  "Hand clumsiness": "conditional",
  "Muscle twitching": "conditional",
  "Post-concussion symptoms": "conditional",
  "Restless legs": "conditional",
  "Hip pain": "primary",
  "Elbow pain": "primary",
  "Wrist pain": "primary",
  "Ankle pain": "primary",
  "Foot pain": "primary",
  "Finger locking": "conditional",
  "Hand numbness at night": "conditional",
  "Achilles pain": "primary",
  "Traumatic joint swelling": "primary",
  "Painful knee replacement": "primary",
  "Morning joint stiffness": "conditional",
  "Painful swollen toe": "primary",
  "Cold-induced finger color change": "conditional",
  "Dry eyes and mouth": "conditional",
  "Widespread body pain": "primary",
  "Proximal stiffness": "conditional",
  "Psoriasis with joint symptoms": "conditional",
  "Inflammatory back stiffness": "conditional",
  "Positive autoimmune test concern": "conditional",
  "Osteoporosis / fragility fracture concern": "conditional",
  "Reduced kidney function result": "conditional",
  "Protein in urine": "conditional",
  "Foamy urine": "conditional",
  "High potassium result": "conditional",
  "Low sodium result": "conditional",
  "Dialysis-related symptoms": "conditional",
  "Kidney stone prevention visit": "conditional",
  "Leg edema with kidney disease": "conditional",
  "Persistent difficult-to-control BP": "conditional",
  "Kidney disease-related itching": "none",
  "Weak urinary stream": "conditional",
  "Difficulty emptying bladder": "conditional",
  "Recurrent urinary infections": "conditional",
  "Testicular pain": "primary",
  "Scrotal lump": "conditional",
  "Erectile difficulty": "conditional",
  "Penile curvature / pain": "primary",
  "Elevated PSA consultation": "conditional",
  "Nighttime urination": "conditional",
  "Pelvic / perineal discomfort": "primary",
  "Painful periods": "primary",
  "Heavy menstrual periods": "conditional",
  "Irregular menstrual cycles": "conditional",
  "Hot flashes / menopausal symptoms": "none",
  "Pain with intercourse": "primary",
  "Vulvar itching / irritation": "conditional",
  "Pelvic organ prolapse concern": "conditional",
  "Fertility concern": "conditional",
  "Nausea in pregnancy": "conditional",
  "Postpartum concerns": "conditional",
  "Low blood sugar episodes": "none",
  "High blood sugar readings": "conditional",
  "Thyroid nodule concern": "conditional",
  "Abnormal thyroid test": "none",
  "Excess facial / body hair": "none",
  "Milky nipple discharge": "conditional",
  "Low libido / hormone concern": "none",
  "Low bone density": "conditional",
  "High calcium result": "conditional",
  "Thyroid replacement follow-up": "none",
  "Eczema flare": "conditional",
  "Psoriasis flare": "conditional",
  "Hives": "conditional",
  "Hair loss patches": "conditional",
  "Fungal nail concern": "conditional",
  "Wart concern": "conditional",
  "Rosacea symptoms": "conditional",
  "Recurrent boils": "conditional",
  "Dandruff / scalp scaling": "none",
  "Contact dermatitis concern": "conditional",
  "Hoarse voice": "conditional",
  "Ear fullness / blocked ear": "conditional",
  "Ear discharge": "conditional",
  "Recurrent nosebleeds": "conditional",
  "Loss of smell": "conditional",
  "Persistent throat clearing": "conditional",
  "Neck lump": "conditional",
  "Recurrent tonsil symptoms": "conditional",
  "Postnasal drainage": "conditional",
  "Jaw pain near ear": "primary",
  "Dry / gritty eyes": "conditional",
  "Itchy watery eyes": "conditional",
  "Eyelid lump": "conditional",
  "Eyelid crusting": "conditional",
  "Gradual cloudy vision": "conditional",
  "Diabetic eye review": "conditional",
  "Glaucoma follow-up concern": "conditional",
  "Eye strain with near work": "conditional",
  "Excessive tearing": "conditional",
  "Contact lens discomfort": "primary",
  "Poor concentration / ADHD concern": "none",
  "Obsessions / compulsions": "none",
  "Trauma-related symptoms": "none",
  "Elevated mood / reduced sleep": "none",
  "Alcohol use concern": "none",
  "Cannabis use concern": "none",
  "Eating / body image concern": "none",
  "Grief-related distress": "none",
  "Medication-related psychiatric symptoms": "none",
  "Irritability / anger episodes": "none",
  "Child with ear pain": "primary",
  "Child with sore throat": "primary",
  "Child with abdominal pain": "primary",
  "Child with constipation": "conditional",
  "Child with bedwetting": "conditional",
  "Child with headache": "primary",
  "Child with wheals / hives": "conditional",
  "Child with limping": "conditional",
  "Child with school attention concerns": "none",
  "Infant with excessive crying": "conditional",
  "Low platelet count": "conditional",
  "High platelet count": "conditional",
  "Low white blood cell count": "conditional",
  "High white blood cell count": "conditional",
  "Iron deficiency concern": "none",
  "High ferritin result": "conditional",
  "High hemoglobin / hematocrit": "conditional",
  "Clot follow-up": "conditional",
  "Vitamin B12 deficiency concern": "conditional",
  "Abnormal protein blood test": "conditional"
};
