// Concise interview labels; educational outlines, not validated diagnostic protocols.
export const generalDetails: Record<string, [string, string, string]> = {
  general: [
    'Baseline health|Main concerns / priorities|Change in function|Energy / stamina|Weight trajectory|Appetite / intake|Sleep pattern|Recent illnesses|Preventive care history|Immunization history|Medication burden|Support needs',
    'Pain|Fever|Chills|Fatigue|Weight loss|Weight gain|Appetite loss|Sleep change',
    'General appearance / nutritional status|Skin / oral mucosa|Heart / lung examination|Gait / functional mobility',
  ],
  cardio: [
    'Exercise tolerance|Chest discomfort pattern|Palpitations pattern|Syncope history|Orthopnea / pillows|Nocturnal dyspnea|Edema pattern|Home BP / pulse|Vascular history|Cardiac procedures|Cardiac medication adherence|Family premature cardiac disease',
    'Chest pressure|Palpitations|Syncope|Orthopnea|Nocturnal dyspnea|Edema|Claudication|Exercise intolerance',
    'Neck veins / carotid assessment|Precordium / heart sounds / murmurs|Peripheral pulses / limb perfusion|Edema / lung bases',
  ],
  resp: [
    'Baseline breathing|Exercise tolerance|Cough pattern|Sputum character|Hemoptysis history|Wheeze triggers|Night symptoms|Smoking / vaping|Occupational inhalation|Inhalers / technique|Oxygen / device use|Prior exacerbations / admissions',
    'Cough|Sputum|Wheeze|Dyspnea|Hemoptysis|Pleuritic pain|Snoring|Apnea',
    'Respiratory effort / speech|Chest symmetry / expansion|Percussion / breath sounds|Clubbing / cyanosis / edema',
  ],
  gi: [
    'Appetite / early satiety|Swallowing|Reflux pattern|Abdominal pain pattern|Nausea / vomiting|Stool frequency / form|GI bleeding history|Weight trajectory|Food relationship|Alcohol / NSAID exposure|Prior endoscopy / surgery|Family GI disease',
    'Dysphagia|Heartburn|Nausea|Vomiting|Bloating|Constipation|Diarrhea|Blood in stool',
    'Oral mucosa / hydration|Abdominal inspection / bowel sounds|Abdominal tenderness / guarding|Liver / spleen / masses as indicated',
  ],
  neuro: [
    'Baseline cognition|Headache pattern|Loss of consciousness|Seizure history|Motor function|Sensory changes|Balance / falls|Speech / swallowing|Vision changes|Bladder / bowel change|Neurologic injury / illness|Functional independence',
    'Headache|Dizziness|Weakness|Numbness|Tremor|Seizures|Memory change|Gait change',
    'Mental status / speech|Cranial nerves|Strength / tone / reflexes / sensation|Coordination / gait when safe',
  ],
  msk: [
    'Pain distribution|Joint swelling|Morning stiffness duration|Activity relationship|Injury / overuse|Range of motion|Functional limits|Instability / locking|Prior fractures|Prior procedures|Assistive devices|Work / sport demands',
    'Joint pain|Swelling|Stiffness|Weakness|Instability|Locking|Back pain|Muscle pain',
    'Posture / gait / alignment|Joint inspection / palpation|Active / passive range of motion|Strength / distal neurovascular status',
  ],
  renal: [
    'Voiding frequency|Nocturia|Stream / hesitancy|Emptying sensation|Leakage pattern|Urine appearance|Urine volume|Fluid intake|Stone / infection history|Kidney disease history|Nephrotoxic exposures|Prior urologic procedures',
    'Dysuria|Urgency|Frequency|Nocturia|Hematuria|Flank pain|Retention|Incontinence',
    'Volume status / edema|Abdominal / suprapubic examination|Costovertebral angle tenderness|Relevant genital / neurologic exam if indicated and consented',
  ],
  repro: [
    'Menstrual history|Last menstrual period|Pregnancy history|Pregnancy possibility|Contraception|Bleeding pattern|Discharge pattern|Pelvic symptoms|Sexual function|STI history / exposure|Screening history|Breast / genital concerns',
    'Pelvic pain|Abnormal bleeding|Discharge|Dyspareunia|Genital lesions|Breast pain|Breast lump|Urinary symptoms',
    'General appearance / abdominal examination|Breast / regional nodes if indicated and consented|External genital exam if indicated and consented|Pelvic examination if indicated with consent / chaperone',
  ],
  endo: [
    'Weight trajectory|Appetite / thirst|Urination pattern|Heat / cold tolerance|Energy / sleep|Skin / hair change|Menstrual / sexual function|Growth / body changes|Home glucose data|Hypoglycemia history|Hormone / steroid exposure|Family endocrine disease',
    'Polyuria|Polydipsia|Heat intolerance|Cold intolerance|Tremor|Weight change|Sweating|Hair change',
    'Weight / body habitus / hydration|Thyroid inspection / palpation|Skin / hair / tremor / reflexes|Feet / sensation when relevant',
  ],
  skin: [
    'Initial lesion|Distribution / spread|Morphology / evolution|Itch / pain|Mucosal involvement|Product exposures|Medication timing|Sun exposure|Occupation / hobbies|Household symptoms|Prior skin disease|Personal / family skin cancer',
    'Itch|Pain|Bleeding|Blistering|Scaling|Drainage|Hair loss|Nail change',
    'Lesion morphology / size / distribution|Surrounding skin / warmth / tenderness|Scalp / nails / mucosa as indicated|Regional nodes / full skin review as indicated and consented',
  ],
  ent: [
    'Hearing baseline|Ear symptoms|Noise exposure|Nasal obstruction|Discharge pattern|Smell / taste|Throat symptoms|Voice changes|Swallowing|Allergy triggers|Tobacco / alcohol exposure|Prior ENT procedures',
    'Ear pain|Hearing loss|Tinnitus|Congestion|Epistaxis|Sore throat|Hoarseness|Dysphagia',
    'External ears / otoscopy|Nasal mucosa / discharge|Oral cavity / oropharynx|Neck / lymph nodes / voice',
  ],
  eye: [
    'Baseline acuity|Laterality|Vision change pattern|Pain / photophobia|Redness / discharge|Flashes / floaters|Field changes|Contact lens use|Trauma / chemical exposure|Ocular procedures|Eye medication use|Family ocular disease',
    'Blurred vision|Vision loss|Eye pain|Redness|Photophobia|Diplopia|Flashes|Floaters',
    'Visual acuity each eye|Pupils / visual fields|Extraocular movements / alignment|External eye / fundus examination as indicated',
  ],
  psych: [
    'Primary concerns|Mood pattern|Anxiety triggers|Sleep / appetite|Energy / concentration|Manic symptoms|Psychotic symptoms|Trauma context|Substance exposure|Past treatment / response|Self-harm / harm-to-others thoughts|Supports / protective factors',
    'Low mood|Anhedonia|Anxiety|Panic|Insomnia|Impulsivity|Hallucinations|Suicidal thoughts',
    'Appearance / behavior / engagement|Speech / mood / affect|Thought process / content / perception|Orientation / attention / insight / judgment',
  ],
  peds: [
    'Caregiver concerns|Birth / gestational history|Growth trajectory|Development / regression|Feeding / nutrition|Urine / stool pattern|Sleep|Immunizations|School / daycare function|Home environment|Prior admissions|Family / caregiver supports',
    'Fever|Poor feeding|Vomiting|Diarrhea|Cough|Rash|Reduced urine|Developmental change',
    'Growth / age-appropriate vital signs|Interaction / hydration / skin|Heart / lungs / abdomen|Age-appropriate neurologic / developmental examination',
  ],
  heme: [
    'Bleeding pattern|Bruising pattern|Fatigue / stamina|Infection pattern|Node enlargement|Fever / sweats|Weight trajectory|Thrombotic history|Transfusion history|Medication exposure|Nutrition / absorption|Family hematologic disease',
    'Fatigue|Pallor|Bruising|Bleeding|Fever|Night sweats|Weight loss|Lymph node swelling',
    'Pallor / jaundice / petechiae|Oral mucosa / bleeding sites|Lymph node regions|Abdomen / liver / spleen as indicated',
  ],
};
export const focusedDetails: [string, string, string, string, string][] = [
  [
    'general',
    'Dehydration / poor intake',
    'Intake amount / duration|Fluid types|Fluid losses|Urine output / color|Last urination|Weight change|Heat / exertion|Access to fluids|Swallowing difficulty|Diuretic use|Baseline kidney / heart disease|Ability to retain fluids',
    'Thirst|Dry mouth|Dizziness|Weakness|Vomiting|Diarrhea|Confusion|Reduced urine',
    'Mental status / orthostatic symptoms|Mucous membranes / capillary refill|Pulse / peripheral perfusion|Abdominal examination / volume status',
  ],
  [
    'cardio',
    'Elevated blood pressure',
    'Home readings / log|Measurement technique|Cuff size / device|Prior baseline|Medication adherence|Recent dose changes|OTC decongestants / NSAIDs|Stimulant exposure|Salt / alcohol intake|Sleep apnea history|Pregnancy / postpartum context|Prior kidney / vascular disease',
    'Headache|Vision change|Chest pain|Dyspnea|Weakness|Confusion|Edema|Reduced urine',
    'Repeat BP with appropriate technique|Fundus / neurologic examination as indicated|Heart / lung examination|Peripheral pulses / volume status',
  ],
  [
    'resp',
    'Sleep apnea concern',
    'Snoring pattern|Witnessed pauses|Gasping / choking|Sleep schedule|Daytime sleepiness|Drowsy driving|Morning symptoms|Weight trajectory|Alcohol / sedatives|Nasal obstruction|Prior sleep testing|PAP use / tolerance',
    'Snoring|Apnea|Fatigue|Morning headache|Dry mouth|Nocturia|Poor concentration|Nonrestorative sleep',
    'Body habitus / neck circumference|Nasal patency / oropharynx|Cardiopulmonary examination|Peripheral edema',
  ],
  [
    'gi',
    'Heartburn / reflux',
    'Burning location|Regurgitation|Meal relationship|Supine / nocturnal pattern|Swallowing difficulty|Painful swallowing|Food impaction|Weight trajectory|Bleeding history|Trigger foods / alcohol|Acid suppression / response|Prior endoscopy',
    'Heartburn|Sour taste|Dysphagia|Odynophagia|Cough|Hoarseness|Melena|Early satiety',
    'Oral / pharyngeal examination|Abdominal tenderness / masses|Nutritional status / pallor|Cardiopulmonary examination for chest symptoms',
  ],
  [
    'neuro',
    'Seizure / seizure-like episode',
    'Witness description|Awareness / responsiveness|Motor pattern / laterality|Event duration|Aura / prodrome|Tongue injury / incontinence|Recovery / confusion|Injury during event|Fever / recent illness|Sleep deprivation / substances|Antiseizure adherence|Prior events / EEG / imaging',
    'Loss of awareness|Jerking|Confusion|Headache|Weakness|Fever|Visual symptoms|Injury',
    'Mental status / return to baseline|Focal neurologic examination|Head / tongue / injury inspection|Meningeal assessment if indicated',
  ],
  [
    'msk',
    'Neck pain',
    'Trauma mechanism|Midline / lateral location|Arm radiation|Posture / work relationship|Movement limitation|Hand dexterity|Limb weakness / numbness|Gait / balance|Bowel / bladder change|Fever / cancer history|Prior cervical procedures|Prior treatment / response',
    'Stiffness|Arm pain|Paresthesia|Weakness|Headache|Gait change|Fever|Bladder change',
    'Posture / tenderness; assess trauma safety first|Cervical motion only when safe|Upper limb strength / sensation / reflexes|Gait / myelopathic signs as indicated',
  ],
  [
    'renal',
    'Urinary incontinence',
    'Stress / urge / continuous pattern|Leak frequency / amount|Pad use|Urgency / warning|Cough / exertion trigger|Nocturnal leakage|Stream / emptying|Fluid / caffeine intake|Obstetric / pelvic surgery history|Mobility / toilet access|Constipation|Medication changes',
    'Urgency|Frequency|Nocturia|Dysuria|Hematuria|Weak stream|Pelvic pressure|Leg weakness',
    'Abdominal / bladder examination|Gait / lower limb neurologic assessment|Pelvic / genital examination if indicated and consented|Cough stress assessment if indicated and consented',
  ],
  [
    'repro',
    'Breast lump / breast pain',
    'Location / laterality|Size / change|Menstrual relationship|Pain pattern|Nipple discharge / character|Skin / nipple change|Pregnancy / lactation|Fever / infection context|Trauma|Prior breast imaging / biopsy|Hormone exposure|Family breast / ovarian cancer',
    'Lump|Tenderness|Redness|Warmth|Nipple discharge|Nipple inversion|Skin dimpling|Axillary swelling',
    'Bilateral inspection with consent / chaperone|Lump location / size / mobility / texture|Nipple / skin examination|Axillary / supraclavicular nodes',
  ],
  [
    'endo',
    'Diabetes follow-up',
    'Home glucose / trends|A1c history|Hypoglycemia frequency|Severe lows / awareness|Medication dose / adherence|Insulin technique / sites|Meals / activity|Sick-day history|Foot wounds / care|Eye / kidney screening history|Neuropathy / sexual function|Medication access / supplies',
    'Polyuria|Polydipsia|Blurred vision|Numbness|Foot pain|Wounds|Sweating|Dizziness',
    'Weight / BP / hydration|Feet / skin / pulses|Protective sensation if appropriate|Injection sites / relevant eye examination',
  ],
  [
    'skin',
    'Acne',
    'Lesion distribution|Comedones / inflammatory lesions|Nodules / cysts|Scarring|Menstrual relationship|Products / cosmetics|Occlusion / friction|Medication / steroid exposure|Prior treatments / duration|Adherence / irritation|Mood / social impact|Pregnancy possibility before treatment planning',
    'Tender lesions|Drainage|Scarring|Pigment change|Itch|Dryness|Irregular menses|Excess hair growth',
    'Lesion type / distribution / severity|Scarring / pigment change|Chest / back involvement with consent|Signs of androgen excess when relevant',
  ],
  [
    'ent',
    'Epistaxis',
    'Side / suspected source|Duration / recurrence|Estimated blood loss|Bleeding ongoing|Pressure technique / response|Trauma / nose picking|Dryness / nasal sprays|Anticoagulant exposure|Other bleeding|Prior cautery / packing|Family bleeding history|Nasal obstruction',
    'Nasal bleeding|Blood in throat|Dizziness|Syncope|Bruising|Gum bleeding|Congestion|Facial pain',
    'Hemodynamic status / pallor|Anterior nasal inspection|Oropharynx for posterior blood|Skin / mucosa for other bleeding',
  ],
  [
    'eye',
    'Flashes / floaters',
    'Eye affected|Sudden / gradual onset|New / baseline floaters|Number / shower of spots|Flash pattern|Curtain / shadow|Field loss|Acuity change|Trauma|High myopia|Prior retinal disease / surgery|Recent eye procedure',
    'Flashes|Floaters|Shadow|Field loss|Blurred vision|Eye pain|Redness|Photophobia',
    'Visual acuity each eye|Confrontation fields / pupils|External eye examination|Retinal examination by qualified examiner as indicated',
  ],
  [
    'psych',
    'Memory / cognitive concern',
    'Patient / collateral concerns|Baseline / trajectory|Affected memory domains|Daily function / finances|Medication management|Driving / getting lost|Fluctuation / acute change|Mood / sleep|Substance / medication exposure|Sensory impairment|Neurologic history|Home safety / supports',
    'Forgetfulness|Confusion|Word-finding difficulty|Personality change|Hallucinations|Low mood|Falls|Sleep change',
    'Attention / orientation / cognition|Speech / affect / behavior|Focused neurologic / gait examination|Hearing / vision barriers to assessment',
  ],
  [
    'peds',
    'Poor growth / weight gain',
    'Growth measurements / trajectory|Birth weight / gestation|Feeding type / schedule|Formula preparation|Latch / transfer|Intake quantity|Vomiting / stool losses|Urine output|Feeding fatigue / sweating|Developmental progress|Food access|Caregiver / feeding interaction',
    'Poor feeding|Vomiting|Diarrhea|Constipation|Cough|Sweating with feeds|Reduced urine|Developmental delay',
    'Plot growth / head circumference as appropriate|Hydration / fat and muscle stores|Oral / cardiac / abdominal examination|Development / observed feeding when appropriate',
  ],
  [
    'heme',
    'Anticoagulant follow-up / bleeding concern',
    'Indication / duration|Agent / dose|Last dose / missed doses|Monitoring results if applicable|Bleeding site / amount|Falls / head injury|New medicines / interactions|NSAID / supplement use|Diet / alcohol changes|Kidney / liver history|Upcoming procedures|Prior bleeding / thrombosis',
    'Bruising|Epistaxis|Gum bleeding|Hematuria|Melena|Headache|Dyspnea|Leg swelling',
    'Vital signs / pallor|Skin / mucosal bleeding|Focused neurologic examination for symptoms / injury|Relevant abdominal / limb examination',
  ],
];
