// Cross-system prompts supplement the system-specific HPI and examination data
// already maintained in the clinical catalog.
export const relatedRosBySystem: Record<string, string[]> = {
  general: [
    'Cardiopulmonary: chest pain, dyspnea, cough, palpitations, edema.',
    'GI/GU: nausea, vomiting, diarrhea, abdominal pain, urinary change.',
    'Neurologic: headache, confusion, dizziness, weakness, syncope.',
    'Skin/MSK: rash, wounds, joint pain, myalgia, focal swelling.',
    'Endocrine/heme: thirst, polyuria, bleeding, bruising, enlarged nodes.',
  ],
  cardio: [
    'Respiratory: dyspnea, cough, wheeze, pleuritic pain, hemoptysis.',
    'Neurologic: dizziness, syncope, focal weakness, speech or vision change.',
    'GI: nausea, vomiting, epigastric discomfort, reflux, early satiety.',
    'General: diaphoresis, fever, fatigue, weight gain or loss.',
    'Vascular/renal: edema, calf pain, claudication, reduced urine output.',
  ],
  resp: [
    'Cardiac: chest pressure, palpitations, orthopnea, edema, syncope.',
    'General: fever, chills, night sweats, fatigue, weight loss.',
    'ENT: congestion, sore throat, postnasal drip, hoarseness, dysphagia.',
    'GI: reflux, vomiting, aspiration/choking, abdominal distention.',
    'Vascular/heme: unilateral calf pain/swelling, bleeding, clot history.',
  ],
  gi: [
    'General: fever, chills, fatigue, night sweats, unintentional weight loss.',
    'Cardiopulmonary: chest pain, dyspnea, cough, palpitations, syncope.',
    'GU/reproductive: dysuria, hematuria, flank/pelvic pain, pregnancy chance.',
    'Heme/skin: bruising, bleeding, jaundice, itching, rash.',
    'Neurologic: dizziness, confusion, weakness, headache after vomiting.',
  ],
  neuro: [
    'Cardiac: chest pain, palpitations, syncope, exercise relation.',
    'General/infectious: fever, chills, weight loss, night sweats, rash.',
    'ENT/eye: hearing change, tinnitus, vision loss, diplopia, neck stiffness.',
    'GI/GU: vomiting, dysphagia, bowel/bladder change, incontinence.',
    'MSK/vascular: neck/back pain, limb pain/swelling, gait or dexterity change.',
  ],
  msk: [
    'Neurologic: weakness, numbness, paresthesia, gait or dexterity change.',
    'General/infectious: fever, chills, fatigue, weight loss, recent infection.',
    'Skin: redness, warmth, rash, wound, drainage, tick exposure.',
    'GU/GI: bowel/bladder change, saddle symptoms, abdominal or flank pain.',
    'Vascular: limb swelling, color/temperature change, claudication.',
  ],
  renal: [
    'General: fever, chills, fatigue, weight change, thirst.',
    'GI: nausea, vomiting, abdominal pain, diarrhea, poor intake.',
    'Reproductive: discharge, bleeding, pelvic/testicular pain, pregnancy chance.',
    'Cardiopulmonary: dyspnea, orthopnea, chest pain, edema.',
    'Neurologic/MSK: weakness, confusion, back pain, saddle or leg symptoms.',
  ],
  repro: [
    'General: fever, fatigue, weight change, night sweats, dizziness.',
    'GI: abdominal pain, nausea/vomiting, bloating, bowel change.',
    'GU: dysuria, frequency, hematuria, flank pain, urinary retention.',
    'Endocrine: heat/cold intolerance, hair/skin change, galactorrhea.',
    'Heme/MSK: bruising, anticoagulants, back pain, leg swelling.',
  ],
  endo: [
    'Cardiac: palpitations, chest pain, exercise intolerance, edema.',
    'Neurologic: headache, vision change, confusion, tremor, numbness.',
    'GI: nausea/vomiting, pain, diarrhea/constipation, appetite change.',
    'GU/reproductive: polyuria, nocturia, menstrual or sexual change.',
    'Skin/MSK: hair/skin change, wounds, weakness, cramps, fractures.',
  ],
  skin: [
    'General/infectious: fever, chills, fatigue, night sweats, weight loss.',
    'Allergy/respiratory: facial swelling, wheeze, dyspnea, throat tightness.',
    'MSK: joint pain/swelling, muscle pain, morning stiffness.',
    'GI/GU: abdominal pain, diarrhea, dark urine, urinary symptoms.',
    'Heme/endocrine: bruising, bleeding, hair loss, temperature intolerance.',
  ],
  ent: [
    'General: fever, chills, fatigue, night sweats, weight loss.',
    'Respiratory: cough, dyspnea, wheeze, stridor, hemoptysis.',
    'Neurologic: headache, facial weakness/numbness, dizziness, gait change.',
    'Eye/dental: vision change, eye pain/swelling, tooth or jaw pain.',
    'GI/allergy: reflux, vomiting, hives, facial swelling, throat tightness.',
  ],
  eye: [
    'Neurologic: weakness, numbness, speech change, dizziness, severe headache.',
    'General/infectious: fever, rash, weight loss, immune suppression.',
    'ENT: sinus/facial pain, nasal symptoms, ear symptoms, jaw pain.',
    'Endocrine/vascular: polyuria, thirst, hypertension, vascular history.',
    'Rheumatologic: joint pain, morning stiffness, oral ulcers, dry mouth.',
  ],
  psych: [
    'Neurologic: headache, seizure, confusion, memory or personality change.',
    'Endocrine: weight change, temperature intolerance, tremor, palpitations.',
    'General: fever, fatigue, pain, sleep change, recent illness.',
    'Substance/medication: alcohol, drugs, caffeine, withdrawal, steroids.',
    'Safety/social: violence, abuse, housing/food access, caregiving, weapons.',
  ],
  peds: [
    'General: fever, poor feeding, lethargy, irritability, growth change.',
    'Respiratory/ENT: cough, congestion, apnea, wheeze, breathing effort.',
    'GI/GU: vomiting, diarrhea, abdominal pain, stool and urine change.',
    'Neuro/MSK: seizure, weakness, altered behavior, gait or limb nonuse.',
    'Skin/heme: rash, bruising, bleeding, color change, swelling.',
  ],
  heme: [
    'Cardiopulmonary: dyspnea, chest pain, palpitations, syncope, hemoptysis.',
    'GI/GU: melena, hematochezia, hematemesis, hematuria, menstrual bleeding.',
    'Neurologic: headache, confusion, focal deficit after bleeding/injury.',
    'General/infectious: fever, night sweats, weight loss, recurrent infection.',
    'Skin/MSK: petechiae, rash, jaundice, limb swelling, bone pain.',
  ],
};
